import Head from "next/head";

import Page1 from "../components/Page1";
import Page2 from "../components/Page2";
import Page3 from "../components/Page3";
import Page4 from "../components/Page4";

// export async function getStaticProps() {
//   const res = await fetch("");
//   const posts = await res.json();
//   return {
//     props: {
//       posts,
//     },
//   };
// }

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>YuiVerse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Page1 />
        <Page2 data={posts} />
        <Page3/>
    <Page4/>
      <footer style={{ textAlign: "center" }}>
        Made by @azzamhfa with ❤ || YuiVerse v2.0 || Last Updated : 11-12-2021
      </footer>
    </div>
  );
}
